### ISSUE TITLE
parallelized on gravity inversion : keyword in Json file

### ISSUE THREAD

**Issue by craigmillernz** [fourndo/SimPEG_Scripts#5]
gravity parallelization requires keyword 'dask', rather than a boolean 'True'. see gravity.py line 27

**Comment by orerocks** [comment]
Resolved in commit [5893e1e94d4e4854ca035f22d606e970001b03c2](https://github.com/simpeg/simpeg/commit/5893e1e94d4e4854ca035f22d606e970001b03c2#diff-981b9d6fb005e7c437c3d74d719e8ddb)
